name: 'pip-install-package'
description: |
  'Find the closest valid version given the package name and target version,
  and python version, and install it by using pip'
branding:
  icon: 'box'
  color: 'purple'

inputs:
  package-name:
    description: 'The package name'
    required: true
  package-version:
    description: 'The package target version'
    required: true
  python-version:
    description: 'The python version'
    required: true
outputs:
  closest-valid-version:
    description:
      'The closest valid package version given the input package version'
    value: ${{ steps.find-version.outputs.closest-valid-version }}

runs:
  using: "composite"
  steps:
    - name: Find poetry
      id: find-poetry
      shell: bash
      run: | 
        if [ -x "$(command -v poetry)" ]; then 
          PREFIX="poetry run " 
        else 
          PREFIX="" 
        fi
        echo "cmd_prefix=${PREFIX}" >> $GITHUB_OUTPUT

    - name: echo output
      id: find-poetry
      shell: bash
      run: | 
        echo ${{ steps.find-poetry.outputs.cmd_prefix }}

    - name: Install dependencies
      shell: bash
      run: |
        pip install "feu[cli]>=0.2.3"

    - name: Find closest valid version
      id: find-version
      shell: bash
      run: |
        VERSION=$(python -m feu find-closest-version --pkg-name=${PACKAGE_NAME} --pkg-version=${PACKAGE_VERSION} --python-version=${PYTHON_VERSION})
        echo ${VERSION}
        echo "closest-valid-version=${VERSION}" >> $GITHUB_OUTPUT
      env:
        PACKAGE_NAME: ${{ inputs.package-name }}
        PACKAGE_VERSION: ${{ inputs.package-version }}
        PYTHON_VERSION: ${{ inputs.python-version }}

    - name: Install package
      shell: bash
      run: |
        python -m feu install --pkg-name=${PACKAGE_NAME} --pkg-version=${PACKAGE_VERSION}
      env:
        PACKAGE_NAME: ${{ inputs.package-name }}
        PACKAGE_VERSION: ${{ steps.find-version.outputs.closest-valid-version }}
