name: 'pip-install-package'
description: |
  'Find the closest valid version given the package name and target version,
  and python version, and install it by using pip'
branding:
  icon: 'box'
  color: 'purple'

inputs:
  package-name:
    description: 'The package name'
    required: true
  package-version:
    description: 'The package target version'
    required: true
  python-version:
    description: 'The python version'
    required: true
  install-prefix:
    description: 'The prefix uses to run the install command'
    required: false
    default: ''
outputs:
  closest-valid-version:
    description:
      'The closest valid package version given the input package version'
    value: ${{ steps.find-version.outputs.closest-valid-version }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        pip install "feu[cli]>=0.2.3"

    - name: Find closest valid version
      id: find-version
      shell: bash
      run: |
        VERSION=$(python -m feu find-closest-version --pkg-name=${PACKAGE_NAME} --pkg-version=${PACKAGE_VERSION} --python-version=${PYTHON_VERSION})
        echo ${VERSION}
        echo "closest-valid-version=${VERSION}" >> $GITHUB_OUTPUT
      env:
        PACKAGE_NAME: ${{ inputs.package-name }}
        PACKAGE_VERSION: ${{ inputs.package-version }}
        PYTHON_VERSION: ${{ inputs.python-version }}

    - name: Install package
      shell: bash
      run: |
        ${INSTALL_PREFIX}python -m feu install --pkg-name=${PACKAGE_NAME} --pkg-version=${PACKAGE_VERSION}
      env:
        INSTALL_PREFIX: ${{ inputs.install-prefix }}
        PACKAGE_NAME: ${{ inputs.package-name }}
        PACKAGE_VERSION: ${{ steps.find-version.outputs.closest-valid-version }}
